---
kind: pipeline
name: lint, test, deploy
workspace:
  path: /app
steps:
  - name: php syntax check
    image: neuronicgames/zapsheets-dev
    commands:
      - for f in $(find /app -name '*.php'); do php -l "$f"; done
  - name: run end-to-end tests
    image: neuronicgames/zapsheets-dev
    environment:
      TEST_SPREADSHEET_ID:
        from_secret: test_spreadsheet_id
      GOOGLE_CREDENTIALS:
        from_secret: google_credentials
    commands:
      - cp .env.example .env
      - echo "$GOOGLE_CREDENTIALS" | base64 -d >> credentials.json
      - composer.phar install
      - composer.phar serve &
      - geckodriver &
      - composer.phar test
  - name: deploy to zapsheets.com/signage
    image: appleboy/drone-scp
    settings:
      host:
        - zapsheets.com
      username: zapsheets
      port: 22
      key:
        from_secret: ssh_zapsheets.com
      target: /home/zapsheets/public_html/signage
      source:
        - .
      when:
        branch:
        - main
trigger:
  event:
    exclude:
    - pull_request
