---
kind: pipeline
name: lint & test
workspace:
  path: /app
steps:
  - name: php syntax check
    image: neuronicgames/zapsheets-dev
    commands:
      - for f in $(find /app -name '*.php'); do php -l "$f"; done
  - name: run end-to-end tests
    image: neuronicgames/zapsheets-dev
    commands:
      - composer.phar install
      - composer.phar serve &
      - geckodriver &
      - composer.phar test
